#
# This file is a mostly a concatenation of `kind_integration.yml` and
# `cloud_integration.yml`, specifically for release.

name: Release
on:
  push:
    branches:
    - test-cache
env:
  GH_ANNOTATION: true
  DOCKER_BUILDKIT: 1
jobs:
  docker_build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        target: [controller]
    name: Docker build (${{ matrix.target }})
    steps:
    - name: Checkout code
      # actions/checkout@v2
      uses: actions/checkout@722adc6
    - name: Set environment variables from scripts
      run: |
        . bin/_tag.sh
        echo ::set-env name=TAG::$(CI_FORCE_CLEAN=1 bin/root-tag)

        . bin/_docker.sh
        echo ::set-env name=DOCKER_REGISTRY::docker.io/etni35
        echo ::set-env name=DOCKER_BUILDKIT_CACHE_REGISTRY::docker.io/etni35
    - name: Login to docker cache registry
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Set up Docker Buildx
      # crazy-max/ghaction-docker-buildx@v3.2.0
      uses: crazy-max/ghaction-docker-buildx@552c9de
    - name: Build & Push Multi Arch Images
      env:
        DOCKER_TRACE: 1
        DOCKER_MULTIARCH: 1
        DOCKER_PUSH: 1
      run: |
        # docker buildx create --driver docker-container --use
        bin/docker-build-${{ matrix.target }}
